### ISSUE TITLE
masquerade works on localhost but not on VPS (development mode)

### ISSUE THREAD

**Issue by dvodvo** [oivoodoo/devise_masquerade#74]
On localhost, using the administrate gem, searching for a user, then calling up the show view and invoking the masquerading function, the application returns and routes to the root_path:
```
Started GET "/users/masquerade/16203?masquerade=syxdpH2UZaHvrzsmpJxBZA&masqueraded_resource_class=User" for ::1 at 2021-01-29 09:21:48 +0100
Processing by Devise::MasqueradesController#show as HTML
  Parameters: {"masquerade"=>"syxdpH2UZaHvrzsmpJxBZA", "masqueraded_resource_class"=>"User", "id"=>"16203"}
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[36mRoleshopuser Load (0.7ms)[0m  [1m[34mSELECT "roleshopusers".* FROM "roleshopusers" WHERE "roleshopusers"."user_id" = $1[0m  [["user_id", 2]]
  ↳ app/controllers/application_controller.rb:268:in `multiple_roles'
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 AND "users"."id" = $2 ORDER BY "users"."id" ASC LIMIT $3[0m  [["id", 16203], ["id", 16203], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Completed 302 Found in 14ms (ActiveRecord: 1.8ms | Allocations: 5109)

Started GET "/" for ::1 at 2021-01-29 09:21:48 +0100
Processing by WelcomeController#home as HTML

```
and the view shown clearly indicates that one is masquerading:
![Screen Shot 2021-01-29 at 9 28 04](https://user-images.githubusercontent.com/716130/106250757-5cc1ba00-6214-11eb-9d51-c48ac4a7409f.png)

However, deploying to a VPS, going through the same steps, there is first a redirection to `Redirected to https://[domain]/users/sign_in` before getting the root_path.

```

Started GET "/users/masquerade/16203?masquerade=oyQZ7gRANUK4uNkB_cSB-A&masqueraded_resource_class=User" for 5.[...]52 at 2021-01-29 08:32:07 +0000
Cannot render console from 5.[...]52! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Devise::MasqueradesController#show as HTML
  Parameters: {"masquerade"=>"oyQZ7gRANUK4uNkB_cSB-A", "masqueraded_resource_class"=>"User", "id"=>"16203"}
  ^[[1m^[[36mUser Load (0.4ms)^[[0m  ^[[1m^[[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2^[[0m  [["id", 2], ["LIMIT", 1]]
  ^[[1m^[[36mRoleshopuser Load (0.6ms)^[[0m  ^[[1m^[[34mSELECT "roleshopusers".* FROM "roleshopusers" WHERE "roleshopusers"."user_id" = $1^[[0m  [["user_id", 2]]
  ↳ app/controllers/application_controller.rb:268:in `multiple_roles'
  ^[[1m^[[36mUser Load (0.5ms)^[[0m  ^[[1m^[[34mSELECT "users".* FROM "users" WHERE "users"."id" IS NULL AND "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2^[[0m  [["id", 16203], ["LIMIT", 1]]
Redirected to https://[domain]/users/sign_in
Completed 302 Found in 11ms (ActiveRecord: 1.5ms | Allocations: 4800)


Started GET "/users/sign_in" for 5.[...]52 at 2021-01-29 08:32:07 +0000
Cannot render console from 5.[...]52! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Devise::SessionsController#new as HTML
  ^[[1m^[[36mUser Load (0.4ms)^[[0m  ^[[1m^[[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2^[[0m  [["id", 2], ["LIMIT", 1]]
Redirected to https://[domain]/
Filter chain halted as :require_no_authentication rendered or redirected
Completed 302 Found in 5ms (ActiveRecord: 0.4ms | Allocations: 1922)


Started GET "/" for 5.[...]52 at 2021-01-29 08:32:07 +0000
Cannot render console from 5.[...]52! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by WelcomeController#home as HTML
```
Being already signed-in, the user is being re-set by devise and the masquerading is that of the admin user (id: 2), not the expected (id: 16203).  This was functioning as per gem design until recently.  I attempted to trace back, but no changes were brought to initial set-up
 
Gemfile.lock
```
    devise_masquerade (1.2.0)
      devise (>= 4.7.0)
      railties (>= 5.2.0)
```
controllers/admin/application_controller.rb
```
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_admin

    def authenticate_admin
      if user_signed_in? &&  current_user.admin?
        respond_to do |format|
          format.html
        end
      else
        redirect_to root_path
      end
    end
```
controllers/application_controller.rb
```
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :multiple_roles
  before_action :masquerade_user!
```
controllers/masquerades_controller.rb 
```
class Admin::MasqueradesController < Devise::MasqueradesController
  protected

  def masquerade_authorize!
    authorize(User, :masquerade?) unless params[:action] == 'back'
  end
end
```

a) is there a way to avoid devise sign-in routing kicking in?
b) how can the same code base be different between localhost and a VPS/url-driven request?

**Comment by dvodvo** [comment]
I've gone through all the existing code base that relate to the home page (where masquerade leads to), permissions, pundit policies (although they are not applied to the user class and its actions) and symlinked files (the only difference is in config/environments/development.rb where `config.hosts` is naturally different on the server. 

I still have a different behaviour on localhost (works per design) to the deployed (re-done about 5 times) code where localhost re-directs to root_path
```
Started GET "/users/masquerade/3?masquerade=ncVziNi5Qe1fjIhvsJNhBQ&masqueraded_resource_class=User" for 127.0.0.1 at 2021-01-30 17:34:08 +0100
Processing by Devise::MasqueradesController#show as HTML
  Parameters: {"masquerade"=>"ncVziNi5Qe1fjIhvsJNhBQ", "masqueraded_resource_class"=>"User", "id"=>"3"}
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 AND "users"."id" = $2 ORDER BY "users"."id" ASC LIMIT $3[0m  [["id", 3], ["id", 3], ["LIMIT", 1]]
Redirected to http://localhost:3000/
Completed 302 Found in 8ms (ActiveRecord: 1.1ms | Allocations: 3621)


Started GET "/" for 127.0.0.1 at 2021-01-30 17:34:08 +0100
```
while the deployed version insists on re-directing to sign_in
```
Started GET "/users/masquerade/3?masquerade=807fTpZLA7zfGomN9jL8zQ&masqueraded_resource_class=User" for 5.[...]52 at 2021-01-30 16:32:45 +0000
Cannot render console from 5.[...]52! Allowed networks: 127.0.0.0/127.255.255.255, ::1
Processing by Devise::MasqueradesController#show as HTML
  Parameters: {"masquerade"=>"807fTpZLA7zfGomN9jL8zQ", "masqueraded_resource_class"=>"User", "id"=>"3"}
  ^[[1m^[[36mUser Load (0.8ms)^[[0m  ^[[1m^[[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2^[[0m  [["id", 2], ["LIMIT", 1]]
  ^[[1m^[[36mUser Load (0.5ms)^[[0m  ^[[1m^[[34mSELECT "users".* FROM "users" WHERE "users"."id" IS NULL AND "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2^[[0m  [["id", 3], ["LIMIT", 1]]
Redirected to https://fidelity.iwant2go2.com/users/sign_in
Completed 302 Found in 8ms (ActiveRecord: 1.3ms | Allocations: 3400)


Started GET "/users/sign_in" for 5.[...]52 at 2021-01-30 16:32:45 +0000
```
I have no way of debugging this, that I know of.  I only have two assumptions/clues:

1 - `masquerade_key` is not being digested properly.
2 - the user db query for the masquered user on localhost is slightly different than with the deployed version
```
    [0m  [["id", 3], ["id", 3], ["LIMIT", 1]]
    [[0m  [["id", 3], ["LIMIT", 1]]
```

**Comment by dvodvo** [comment]
This issue can be closed.  Stubborn me had not passed the issues with fine tooth and comb.  [this issue](https://github.com/oivoodoo/devise_masquerade/issues/58)  points to a solution

The gist appears to be that caching on localhost != caching in development on VPS
```
   touch tmp/restart.txt
   touch tmp/caching-dev.txt
```
did the trick, as per the suggestion linked above.

There is also the troubleshooting on the Readme  which sailed over my head.
